## NumPy Arrays

In the following, the term 'array' refers to `ndarray` objects. Avoid loops whenever possible. Let $a, b$ two numbers with $a \leq b$. The colloquial phrases 

* from a to b
* between a and b

include **both** numbers $a$ and $b$. 


### Exercise 0

Import NumPy

In [3]:
# code

import numpy as np

---
### Exercise 1
Write a function that converts Python lists or tuples to NumPy arrays. Test for which Python lists / tuples the conversion works (e.g. nested lists and so on, lists consisting of items of different types, and so on).

In [4]:
# code

test = [x for x in range(20)]
print(test)
test = np.array(test)
print(test)
print(type(test))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


---
### Exercise 2
Create an array of all the even integers from 60 to 90.

In [5]:
# code
test = np.arange(60,91)
print(test)

[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89 90]


---
### Exercise 3
Create an array with values from 25 to 50 and print all values except the first and last. Use two statements, one for creating the array, the other for printing.

In [6]:
# code
test = np.arange(25,51)
print(test[1:-1])

[26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


---
### Exercise 4

Create an array of length 10 with values evenly distributed between 15 and 60.

In [7]:
# code
test = np.linspace(15,60,10)
print(test)
test = np.arange(10,61,50/9)
print(test)

[15. 20. 25. 30. 35. 40. 45. 50. 55. 60.]
[10.         15.55555556 21.11111111 26.66666667 32.22222222 37.77777778
 43.33333333 48.88888889 54.44444444 60.        ]


---
### Exercise 5

Create a $(5 \times 5)$ identity matrix (see NumPy docs) and a $(5 \times 5)$ matrix of ones. Add both matrices and print the sum.

In [8]:
# code
id_matrix = np.eye(5)
one_matrix = np.ones((5,5))
sum = id_matrix + one_matrix
print(sum)
print()
print(np.sum(id_matrix) + np.sum(one_matrix))

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]

30.0


---
### Exercise 6

Write a function that accepts two arrays of the same shape and returns their Euclidean distance. Test the correctness of your implementation by comparing it with the function `np.linalg.norm`.

In [9]:
# code
import math
def euclid_dist(X, Y):
    if(X.shape != Y.shape):
        print("Not the same shape")
        return
    dist = math.sqrt(np.sum((X-Y)**2))
    
            
    return dist
    
X = np.eye(5)
Y = np.linspace(10,50, 25).reshape(5,5)

print(euclid_dist(X=X, Y=Y))
print(np.linalg.norm((X-Y)))
    

160.67392791337093
160.67392791337093


---
### Exercise 7

The following figure illustrates the max pooling operation on a 2D array `X` (left) of shape $(4, 4)$ with a max-pool filter of `pool_size` $(2, 2)$. The output of max pooling is a 2D array (right) of shape $(2, 2)$ containing the maximum values of the corresponding blocks of the same color in `X`. 

<div style="text-align: left;">
<img src="./img/maxpool.png" alt="Image" width="300" />
</div>

Write a max pooling function that takes as input a 2D array `X` and a tuple `pool_size`. The function divides the input `X` into non-overlapping blocks of size `pool_size` and returns a new matrix where each element is the maximum value of the corresponding block in the input matrix. Assume that `X` can be partitioned into non-overlapping blocks of the specified `pool_size`. 


Image source. [[>](https://computersciencewiki.org/index.php/File:MaxpoolSample2.png)]

In [21]:
# code
"""
def max_pooling(X, poolsize=(2,2)):
    list = [0 for i in range(X.size//(poolsize[0] * poolsize[1]))]
    for i in range(X.size//(poolsize[0] * poolsize[1])):
        """
    
original_matrix = np.array([12,20,30,0,8,12,2,0,34,70,37,4,112,100,25,12]).reshape(4,4)
#print(max_pooling(original_matrix))

0 0
0 1
0 2
0 3
0 4
0 5
0 6
0 7
1 0
1 1
1 2
1 3
1 4
1 5
1 6
1 7
2 0
2 1
2 2
2 3
2 4
2 5
2 6
2 7
3 0
3 1
3 2
3 3
3 4
3 5
3 6
3 7
4 0
4 1
4 2
4 3
4 4
4 5
4 6
4 7
5 0
5 1
5 2
5 3
5 4
5 5
5 6
5 7
6 0
6 1
6 2
6 3
6 4
6 5
6 6
6 7
7 0
7 1
7 2
7 3
7 4
7 5
7 6
7 7
None
