In [1]:
import numpy as np

## NumPy: Random Sampling [[docs](https://numpy.org/doc/stable/reference/random/index.html)]



---
### Seeds

Compare the output of cells (a)-(d)

In [2]:
# a)
np.random.rand(3)

array([0.91665977, 0.05543121, 0.2929152 ])

In [3]:
# b)
np.random.rand(3)

array([0.83998556, 0.61364246, 0.18257316])

In [4]:
# c)
np.random.seed(13)
np.random.rand(3)

array([0.77770241, 0.23754122, 0.82427853])

In [5]:
# d)
np.random.seed(13)
np.random.rand(3)

array([0.77770241, 0.23754122, 0.82427853])

The random numbers generated in (a) and (b) are different, while the random numbers in (c) and (d) are identical. This is because a seed has been set to a user-defined positive integer, to ensure that the same sequence of random numbers is generated.

The random numbers are generated using a pseudorandom number generator (PRNG). This is a deterministic algorithm that generates numbers that approximate the properties of random numbers. The sequence of numbers generated by the PRNG is determined by an initial value called the seed.

The seed is a number or vector that is used to initialize the PRNG. It completely determines the sequence of numbers generated by the PRNG. Reinitializing the PRNG with the same seed will produce the same sequence of numbers.

The purpose of using a seed is to allow us to replicate results and compare different algorithms. By setting the same seed before running an algorithm, we can ensure that the same sequence of random numbers is generated, allowing us to compare results across different runs.

The code 

```python
    np.random.seed(number)
```

sets the seed for NumPy’s PRNG to the specified number. This means that the sequence of random numbers generated by NumPy’s PRNG will be determined by this seed value. If the same seed is used again in the future, the same sequence of random numbers will be generated.

The code

```python
    np.random.seed()
```

 sets the seed for NumPy’s PRNG using the system time as the seed value. This means that each time this line of code is executed, a different sequence of random numbers will be generated, since the system time changes.

If the user does not explicitly set a seed for NumPy’s PRNG, the PRNG will be initialized with a default seed value derived from the system time the first time it is used.

### Remark: `default_rng`

The `np.random.seed` function sets the global random seed for NumPy's PRNG. This affects all uses of the `np.random` module and is fine for small projects. However, in larger projects with multiple imports that could also set the seed, different seeds could result in non-reproducible results.

To avoid this problem, you can use a local PRNG for your own code by creating an instance of `np.random.default_rng`. This is useful in larger projects where multiple modules can be set the global random seed using `np.random.seed`.

In [6]:
# Example usage:
seed = 0                                # set your seed
rng = np.random.default_rng(seed)       # create local PRNG (can be called without seed)
x = rng.random(3)                       # generate random numbers

---
## Hint

Explore the documentation and experiment with the functions as suggested in the following exercises.

---
### Exercise

Create a $(3\times 4)$ matrix with random numbers drawn from a normal distribution with mean one and standard deviation 0.5

In [7]:
# code

---
### Exercise

Create a $(2 \times 3\times 4)$ array with random integers drawn from the interval $[5, 10]$.

In [8]:
# code

---
### Exercise

Create an array of integers from 0 to 9 (inclusive). Randomly permute the array. What is the difference between permuting and shuffling in NumPy?

In [9]:
# code

---
### Exercise 

Create a 1D array with 10 integers from 0 to 9 (inclusive). Randomly choose 6 elements from the array with and without replacement. 

In [10]:
# code