In [1]:
import numpy as np

## Broadcasting

**Remark:** For convenience, explanations omit commas in ndarray objects.

---
### Exercise 1:

Predict the output and explain step-by-step how broadcasting rules are applied:

In [2]:
A = np.ones((2, 3))
x = np.arange(3)

A * x

array([[0., 1., 2.],
       [0., 1., 2.]])

---
### Exercise 2:

Predict the output and explain step-by-step how broadcasting rules are applied:

In [3]:
A = np.arange(3).reshape(3, 1)
x = np.arange(3)

A - x

array([[ 0, -1, -2],
       [ 1,  0, -1],
       [ 2,  1,  0]])

---
### Exercise 3:

Predict the output and explain step-by-step how broadcasting rules are applied:

In [4]:
A = np.ones((3, 2))
x = np.arange(3)

A + x

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

---
### Exercise 4:

Predict the output and explain step-by-step how broadcasting rules are applied:

In [5]:
A = np.arange(4).reshape(2, 1, 2)
x = np.arange(3).reshape(3, 1)
A + x

array([[[0, 1],
        [1, 2],
        [2, 3]],

       [[2, 3],
        [3, 4],
        [4, 5]]])

---
### Exercise 5:

Mean center the rows of a matrix $A \in \mathbb{R}^{m \times n}$. The elements of the mean-centered matrix are given by

$$
    \bar{a}_{ij} = a_{ij} - \mu_i,
$$

where 

$$
    \mu_i = \frac{1}{n} \sum_{j=1}^n a_{ij}
$$

is the mean of the i-th row of $A$. 

<br>

Perform row-wise mean centering on the following matrix:

In [ ]:
A = np.linspace(1, 8, 8).reshape(4,2)
print(A)

---
### Exercise 6: Sinkhorn's algorithm

Suppose that $X = (x_{ij})$ is a square matrix with non-negative elements $x_{ij} \in \mathbb{R}$. Consider Sinkhorn's algorithm that alternates between row and column normalization:

```
    repeat
    
        # row normalization
        for each row i of matrix X
            for each column j of matrix X
                X[i,j] = X[i,j] / sum(X[i,:])  # sum(X[i,:]) = total sum of i-th row
        
        # column normalization
        for each column j of matrix X
            for each row i of matrix X
                X[i,j] = X[i,j] / sum(X[:,j])  # sum(X[:,j]) = total sum of j-th column
    
    until termination
```            

Write a function `sinkhorn(X)` that returns the matrix obtained by applying Sinkhorn's algorithm to the square matrix `X` with non-negative elements. Test your implementation with different square matrices and print the sum of each row and each column. What do you observe?