In [4]:
import numpy as np

## Shape Manipulations

This notebook does not only contain exercises but also covers useful new material on shape manipulations. 

---
### Overview

| Method/Function     | Type      | Reference  | Returns
|---------------------|-----------|------------|----------------------------------------|
| `ndarray.flatten`   | method    | copy       | flattened copy of input array          |
| `ndarray.ravel`     | method    | view       | flattened view of input array          |
| `numpy.ravel`       | function  | view       | flattened view of input array          |
| `ndarray.resize`    | method    | in-place   | reshaped input array of specified size |
| `numpy.resize`      | function  | copy       | reshaped copy of specified size        |
| `ndarray.reshape`   | method    | view       | reshaped view of same size             |
| `numpy.reshape`     | function  | view       | reshaped view of same size             |
| `ndarray.transpose` | method    | view       | array with permuted axes               |
| `numpy.transpose`   | function  | view       | array with permuted axes               |
| `ndarray.T`         | method    | view       | array with permuted axes               |


---
### Exercise 1

Apply `ndarray.reshape` to change the shape of `x` into a 2D array in all possible forms

In [5]:
x = np.arange(10)

In [9]:
# code

---
### Exercise 2

Predict the output:

In [10]:
x = np.arange(10).resize(5, 2)
print(x)

None


---
### Exercise 3

Flatten the following array in different ways and predict the output:

In [11]:
A = np.arange(24).reshape(3, 2, 4)
print(A)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [16]:
# code

print(A.flatten())
print(A.ravel())
print(A.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


---
### Let NumPy do the Work

+ `reshape` admits one negative integer as argument

+ in this case, NumPy infers the correct number from the other dimensions

+ **Note:** `resize` does not accept negative integers as arguments 

<br>

**Example:**

In [18]:
x = np.arange(10).reshape(-1, 5)    # NumPy infers 10/5 = 2 rows
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [19]:
x = np.arange(10).reshape(5, -1)    # NumPy infers 10/5 = 2 columns
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


---
### Add and Axis

Adding an axis is occassionally requires, e.g. in sklearn and PyTorch. An example is provided in the broadcasting exercises. 

In [20]:
x = np.arange(10)
print('shape :', x.shape)

shape : (10,)


**Adding an axis from the right**

The desired shape is (10, 1), that is the resulting 2D array looks like a column vector.

In [21]:
y = x.reshape(-1, 1)
print(y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [22]:
y = x[:, np.newaxis]
print(y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


**Adding an axis from the left**

The desired shape is (1, 10), that is the resulting 2D array looks like a row vector.

In [23]:
y = x.reshape(1, -1)
print(y)

[[0 1 2 3 4 5 6 7 8 9]]


In [29]:
y = x[np.newaxis, :]
print(y, y.shape)

[[0 1 2 3 4 5 6 7 8 9]] (1, 10)


#### **np.newaxis**

`np.newaxis` is a pseudo-index that uses the slicing operator to add an additional dimension to the array. Like `reshape`, the resulting array is a view. `np.newaxis` is equivalent to the `None` object, so `None` can be used in place of `np.newaxis` to add axes. 

In [30]:
print(np.newaxis is None)

True
