In [1]:
import numpy as np

---
## Indexing

Solve the following exercises without using loops and without inserting the values manually. Let $a, b$ two numbers with $a \leq b$ The colloquial phrases 

* from a to b
* between a and b

include **both** numbers $a$ and $b$. 

---
### Exercise 1

Create an array with values from 0 to 10 and set even numbers to zero.

In [14]:
# code

X = np.arange(0,11)
mask = X%2 == 0
X[mask] = 0
print(X)

[0 1 0 3 0 5 0 7 0 9 0]


---
### Exercise 2

Create an array with values from 0 to 10 and change the sign of the numbers from 3 to 7. 

In [19]:
# code
X = np.arange(0,11)
mask = X%4 == 3
X[mask] = -X[mask]
print(X)

[ 0  1  2 -3  4  5  6 -7  8  9 10]


---
### Exercise 3

Select the values 6, 7, 17, and 18 from the given 2D array using a single statement. 

In [21]:
x = np.arange(25).reshape(5, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [46]:
# code



---
### Exercise 4: Finding Top Math Students

In this exercise, you will work with a dataset of student grades stored in a 2D array. Each row represents a student and each column represents a subject. The values in the array are the scores of the students in each subject. The first column refers to math.

**Task:**

1. Find all the students who scored above 90 in math.

2. Print all the scores of the top math students.

In [39]:
grades = np.array([[85, 88, 92],
                   [78, 95, 80],
                   [91, 88, 84],
                   [92, 97, 89]])

print(grades)

[[85 88 92]
 [78 95 80]
 [91 88 84]
 [92 97 89]]


In [48]:
# code

mask = grades[:, 0] > 90
top_students = grades[mask]
print(top_students)

[[91 88 84]
 [92 97 89]]


---
### Exercise 5: Predicting Class Labels

In this exercise, you will create two arrays representing class labels and scores for each class. Then, you will use the scores to make predictions and compute the error rate between the true labels and the predictions.

1. Create a 1D array `y` with 1,000 random integers from 0 to 2. This array represents the true class labels from three classes.

2. Create a 2D array `scores` of shape 1,000 x 3 with random values uniformly drawn from the interval [0, 1]. This array represents the scores for each class, where `scores[i, j]` is the score of class `j` for the `i-th` example.

3. For each row `i` of array `scores`, select the index `j` for which `scores[i, j]` is the maximum over all `scores[i,:]` in the i-th row. Collect the results in a 1D array `y_pred` with 1,000 elements.

4. Compute the error rate between the true labels `y` and the predictions `y_pred`.


In [57]:
# code

y = np.random.randint(0,3, size=1000)
scores = np.random.uniform(0,1.01, size=(1000,3))

y_pred = np.array(np.max(a=scores, axis=1))
#TODO prediction label

[0.9353464  0.95157836 0.7564337  0.79659702 0.95817542 0.8309081
 0.99041516 0.72197551 0.35001078 0.2706836  0.9939303  0.96462191
 0.70204256 0.73053218 0.64959629 0.80544385 0.86573865 1.00887033
 0.85223549 0.76725144 0.49363935 0.8508051  0.78656568 0.83782216
 0.88898286 0.65726793 0.54862354 0.68064127 0.78521162 0.82970067
 0.66232208 0.86793927 0.71755037 0.6691591  0.8229615  0.56896796
 0.74562783 0.92037269 1.00945587 0.96860504 0.92558241 0.8728582
 0.99866558 0.12227402 0.88463282 0.27811328 0.96667124 0.57988806
 0.83731786 0.69278134 0.96872571 0.60722625 0.87607097 0.3538211
 0.74536992 0.89064529 1.00530848 0.6073305  0.78939299 0.57553326
 0.79754973 0.69258613 1.0039073  0.9996916  0.26240157 0.69883345
 0.56898829 0.80894741 0.66598823 0.57901332 0.81313711 0.69175751
 0.44145775 0.85933154 0.54211077 0.59293857 0.46920943 0.59641411
 0.92589449 1.00251073 0.58142411 0.87687842 0.7829321  0.80810512
 0.77831106 0.94749326 0.98770602 0.57518754 0.92377166 0.8349088