In [1]:
import numpy as np


## 4. Shape Manipulations


1. Overview

2. `flatten` and `ravel`

3. `resize` and `reshape`

4. `transpose`

5. Appendix A


<br>

#### Summary

| Method/Function    | Type      | Reference | Returns
|--------------------|-----------|-----------|-------------------------------|
| `ndarray.flatten`  | method    | copy      | flattened copy of input array |
| `ndarray.ravel`    | method    | view      | flattened view of input array |
| `numpy.ravel`      | function  | view      | flattened view of input array |
||
| `ndarray.resize`   | method    | in-place  | reshaped input array of specified size |
| `numpy.resize`     | function  | copy      | reshaped copy of specified size        |
| `ndarray.reshape`  | method    | view      | reshaped view of same size             |
| `numpy.reshape`    | function  | view      | reshaped view of same size             |
||
| `ndarray.transpose` | method   | view      | array with permuted axes |
| `numpy.transpose`   | function | view      | array with permuted axes |
| `ndarray.T`         | method   | view      | array with permuted axes |


---

### 3.1. Overview


**Application example:**

+ Transform data into the required format for different algorithms 

+ The MNIST dataset consists of images of handwritten digits
    
+ Each image is represented by a 784-dimensional feature vector of pixel intensities
    
+ 1D representation is convenient for many machine learning classifiers
    
+ However, conv-nets require that MNIST images to be represented as 28 x 28 pixel matrices
    
+ Use shape manipulations to easily transform the data from one representation to the other


<br>

**Organization of NumPy Arrays:** 

+ N-dimensional arrays consist of 

    + raw array data (data buffer) stored as a **contiguous block** in memory

    + metadata that describes how to interpret the data in the data buffer

+ Memory layout

    + elements can be stored in **row-major order** (C) or in **column-major order** (Fortran)

    + an indexing code maps an N-dimensional index into a one-dimensional index

+ Metadata

    + offset and size information

    + number of dimensions

    + stride: separation between elements for each dimension

    + ...
    
<br>

**Example:** Internally, the elements of the following matrix

$$
A = \begin{pmatrix}
0 & 1 \\
2 & 3
\end{pmatrix}
$$

can be stored contiguously in memory, for example in 

+ row-major order `0 1 2 3` as in C or in 

+ column-major order `0 2 1 3` as in Fortran

Here, the elements are stored in row-major order as in C (C contiguous).

In [2]:
A = np.array([[0, 1, 2], [2, 3, 3]]) 

print('matrix A:')
print(A)

print()
print(A.flags)
print('strides:', A.strides)

matrix A:
[[0 1 2]
 [2 3 3]]

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

strides: (24, 8)


**Shape manipulations**

+ Do not alter the memory layout

+ Alter the metadata associated with the array

<br>

**Copies and Views:** 

+ Copies 
    
    + duplicate the data buffer and metadata

    + changes made to the copy do not reflect on the original array

+ Views 

    + access the original data buffer by changing the metadata (e.g. stride)

    + create a new way of looking at the data

    + faster and less memory consuming than creating copies

<br>

**Note:** 

+ Some methods/functions aim to return a view may return a copy instead

+ Copies are returned if a view is not possible

---
### 4.2. `flatten` and `ravel`


#### **4.2.1. Overview**

The `flatten` and `ravel` function / method *flatten* a multidimensional array onto a single axis.


| Method/Function    | Type      | Reference | Returns
|--------------------|-----------|-----------|-------------------------------|
| `ndarray.flatten`  | method    | copy      | flattened copy of input array |
| `ndarray.ravel`    | method    | view      | flattened view of input array |
| `numpy.ravel`      | function  | view      | flattened view of input array |


<br>

**Note:** `ravel` 

+ returns a flattened view of the input array whenever possible, and a copy otherwise

+ is usually faster than `flatten`

+ there is no `np.flatten()`


<br>

#### **4.2.2. Example**
By default, flatten and ravel flatten in row-major order. 

<div style="text-align: left;">
<img src="./figs/flatten.png" alt="tensors" width="300">
</div>

#### **4.2.3 `flatten`**

In [3]:
# input 2D array to be flattened
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [4]:
# flatten
a_flatten = A.flatten()
print(a_flatten)

[1 2 3 4 5 6]


The `flatten` method returns a copy: 

In [5]:
# modify flattened arrary
a_flatten[0] = -1

# check effect
print()
print('original:')
print(A)

print()
print('flattened:')
print(a_flatten)

print()
print('a_flatten is a view of A?', np.shares_memory(a_flatten, A))


original:
[[1 2 3]
 [4 5 6]]

flattened:
[-1  2  3  4  5  6]

a_flatten is a view of A? False


#### **4.2.3. `ravel`** (view)

In [6]:
# input 2D array to be flattened
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [7]:
# ravel function
a_ravel = np.ravel(A)
print(a_ravel)

[1 2 3 4 5 6]


The `ravel` function returns a view:

In [8]:
# modify raveled arrary
a_ravel[0] = -1

# check effect
print()
print('original:')
print(A)

print()
print('raveled:')
print(a_ravel)

print()
print('a_ravel is a view of A?', np.shares_memory(a_ravel, A))



original:
[[-1  2  3]
 [ 4  5  6]]

raveled:
[-1  2  3  4  5  6]

a_ravel is a view of A? True


---

### 4.3. `resize` and `reshape`


#### **4.3.1. Overview**

Both `resize` and `reshape` functions / methods change the shape of an array. The `resize` function / method can also change the size of the input array.


| Method/Function   | Type     | Reference | Returns
|-------------------|----------|-----------|----------------------------------------|
| `ndarray.resize`  | method   | in-place  | reshaped input array of specified size |
| `numpy.resize`    | function | copy      | reshaped copy of specified size        |
| `ndarray.reshape` | method   | view      | reshaped view of same size             |
| `numpy.reshape`   | function | view      | reshaped view of same size             |

<br>

**Note:** 

+ `ndarray.resize` resizes in-place

+ `ndarray.resize` with different size raises an error if the input array is referenced or a reference

+ `reshape` returns a view of the input array if possible, otherwise, it returns a copy

+ `resize` and `reshape` are more general than `flatten` and `ravel`

#### **4.3.2. `ndarray.resize`** (in-place)

Resize array in-place to the same size but different shape:

In [11]:
# input array
x = np.arange(6)
print('input array x:')
print(x)

input array x:
[0 1 2 3 4 5]


In [13]:
# resize
x.resize((2, 3))

print('resized array x:')
print(x)

resized array x:
[[0 1 2]
 [3 4 5]]


#### **4.3.3. `numpy.resize`** (copy)

Return resized copy of input array of the same size but different shape:

In [14]:
# input array
x = np.arange(6)

print('input array x:')
print(x)

input array x:
[0 1 2 3 4 5]


In [15]:
# resize
A = np.resize(x, (2, 3))

print('resized array A:')
print(A)

print()
print('A is a view of x?', np.shares_memory(A, x))

resized array A:
[[0 1 2]
 [3 4 5]]

A is a view of x? False


#### **4.3.4. `ndarray.reshape`** (view)

Return view of reshaped input array of the same size:

In [16]:
# input array to be reshaped
x = np.arange(6)
print('input array x:')
print(x)

input array x:
[0 1 2 3 4 5]


In [17]:
# reshape
print('reshaped array A:')
A = x.reshape((2, 3))
print(A)

print()
print('A is a view of x?', np.shares_memory(A, x))

reshaped array A:
[[0 1 2]
 [3 4 5]]

A is a view of x? True


---
### 4.3. `transpose`

The `transpose` function / method returns an array with its axes reversed by default. For a 2-D array, this is the standard matrix transpose. For an N-dimensional array, if axes are given, their order indicates how the axes are permuted. 


| Method/Function     | Type     | Reference | Returns
|---------------------|----------|-----------|--------------------------|
| `ndarray.transpose` | method   | view      | array with permuted axes |
| `numpy.transpose`   | function | view      | array with permuted axes |
| `ndarray.T`         | method   | view      | array with permuted axes |

<br>

#### **Example** (2D Array)

In [18]:
# input array to be transposed
A = np.arange(6).reshape(2, 3)
print(A)

[[0 1 2]
 [3 4 5]]


In [19]:
# transpose
B = A.transpose()

print(B)
print()
print('B is a view of A?', np.shares_memory(B, A))

[[0 3]
 [1 4]
 [2 5]]

B is a view of A? True


---
---
## Appendix A

Appendix A explores the shape manipulation functions and methods introduced in this notebook. 

---
###  A.1. `ravel` (copy)

When `ravel` fails to return a view, it returns a copy. 

In [20]:
# input 2D array to be flattened
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [23]:
# 1d column sliced from A
col = A[:, 1]

# 1d row sliced from A
row = A[1, :]

print('col :', col)
print('row :', row)
print()

print('col is a view of A?', np.shares_memory(col, A))
print('row is a view of A?', np.shares_memory(row, A))
print()

print('col is contiguous:', col.flags['C_CONTIGUOUS'])
print('row is contiguous:', row.flags['C_CONTIGUOUS'])

col : [2 5]
row : [4 5 6]

col is a view of A? True
row is a view of A? True

col is contiguous: False
row is contiguous: True


The 2D array `A` is stored in row-major order. A slice that selects a row of `A` results in a contiguous view, while a slice that selects a column results in a non-contiguous view of the data. Applying `ravel` gives a view of `row` and a copy of `col`:

In [25]:
col_ravel = np.ravel(col)
row_ravel = np.ravel(row)

print('col_ravel is a view of col?', np.shares_memory(col_ravel, col))
print('row_ravel is a view of col?', np.shares_memory(row_ravel, row))
print('row_ravel is a view of A?', np.shares_memory(row_ravel, A))


col_ravel is a view of col? False
row_ravel is a view of col? True
row_ravel is a view of A? True


**Note:** `row` and `col` are flat (1D arrays). Applying `ravel` on a 1D array returns an unchanged view (or copy) of the original array.

---
### A.2. `resize` to a larger size


#### A.2.1. `numpy.resize`

Resize array to a larger size using the `numpy.resize` function:

In [27]:
# input array to be resized
x = np.arange(6)
print('input array x:')
print(x)
print()

# resize
print('resized array A:')
A = np.resize(x, (3, 4))
print(A)

print()
print('A is a view of x?', np.shares_memory(A, x))

input array x:
[0 1 2 3 4 5]

resized array A:
[[0 1 2 3]
 [4 5 0 1]
 [2 3 4 5]]

A is a view of x? False


The `numpy.resize` returns a copy when reshaping to a larger size. The copy replicates the elements of the input array. 



#### A.3.2. `ndarray.resize` 

Resize array in-place to a larger size using the `ndarray.resize` method:

In [28]:
# input array
x = np.arange(6)

print('input array x:')
print(x)
print('id :', id(x))

input array x:
[0 1 2 3 4 5]
id : 123842498032912


In [29]:
# resize
x.resize((4, 6))

print('resized array x:')
print(x)
print()
print('id :', id(x))

resized array x:
[[0 1 2 3 4 5]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

id : 123842498032912


The `ndarray.resize` method resizes in-place by adding zeros.


**Note:**

+ Exercise: explore `resize` to smaller size

+ `numpy.resize` to a different size raises an error if input array is referenced or is a reference



In [30]:
x = np.arange(6)
a = x               

# error: different size and 'x' is referenced by 'a'
#x.resize((4, 3))

# error: different size and 'a' references x
#a.resize(4, 3)


---
### A.4. `transpose` (3D Array - Default Order)

In [32]:
# input array to be transposed
A =  np.random.randint(0, 10, (2, 3, 4))
print(A)

[[[9 7 9 5]
  [4 9 0 8]
  [7 0 3 2]]

 [[1 4 5 7]
  [0 0 8 3]
  [0 1 0 6]]]


In [33]:
# transpose
B = A.transpose()

print('Shape of B:', B.shape)
print()
print('Array B:')
print(B)
print()
print('B is a view of A?', np.shares_memory(B, A))

Shape of B: (4, 3, 2)

Array B:
[[[9 1]
  [4 0]
  [7 0]]

 [[7 4]
  [9 0]
  [0 1]]

 [[9 5]
  [0 8]
  [3 0]]

 [[5 7]
  [8 3]
  [2 6]]]

B is a view of A? True


---
### A.5. `transpose` (3D Array - Specified Order)

In [34]:
# array to be transposed
A =  np.random.randint(0, 10, (2, 3, 4))
print(A)

[[[8 1 7 3]
  [6 8 2 1]
  [6 2 2 2]]

 [[0 9 7 4]
  [1 8 3 9]
  [7 7 5 9]]]


In [36]:
# transpose in given order
B = A.transpose([1, 0, 2])

print('Shape of B:', B.shape)
print()
print('Array B:')
print(B)
print()
print('B is a view of A?', np.shares_memory(B, A))

Shape of B: (3, 2, 4)

Array B:
[[[8 1 7 3]
  [0 9 7 4]]

 [[6 8 2 1]
  [1 8 3 9]]

 [[6 2 2 2]
  [7 7 5 9]]]

B is a view of A? True
