In [1]:
import numpy as np


## 6. Advanced Indexing


1. Overview

2. Boolean indexing

3. Fancy indexing

4. Summary


---

### 6.1. Overview


NumPy offers three types of indexing: 

+ **Multidimensional indexing:** indexing of higher dimensional arrays with a single pair of square brackets (see Section 2.4).

+ **Boolean indexing:** indexing of arrays using boolean masks.

+ **Fancy indexing:** indexing of arays using other arrays or lists of indices.

In this section, we consider boolean and fancy indexing.

---
### 6.2. Boolean Indexing


**Principle:** Select data based on a condition



**Application examples**

+ Filtering customer data

    + Given: dataset of customer information

    + Goal: select only the customers from a certain region, age, gender, ...

+ Detecting outliers

    + Given: dataset of patient information

    + Goal: select all patients with abnormal blood pressure


**Boolean Indexing** 

Boolean indexing selects data based on a condition using boolean masks.

+ Step 1: Create Boolean Mask

    + array of the same shape as the original array

    + contains `True` values for which the condition holds
    
    + contains `False` values for which the condition is violated

    + use comparision operators (<, >, ==, etc.) or functions that return Boolean arrays


+ Step 2: Apply Boolean Mask

    + use Boolean mask to index the original array

    + resulting array contains only the elements for which the mask is `True`

    + Boolean masks can also be used to modify elements in the original array

**Example:**

In [2]:
# base array to be indexed
x = np.arange(6)
print('x :', x)

x : [0 1 2 3 4 5]


In [3]:
# boolean mask as list of True and False values
mask = [True, False, True, False, True, False]
y = x[mask]
print('y :', y)

y : [0 2 4]


In [4]:
# boolean mask as expression that evaluates to Boolean array
mask = x % 2 == 0
print('mask :', mask)

y = x[mask]
print('y    :', y)

mask : [ True False  True False  True False]
y    : [0 2 4]


In [5]:
# combine Boolean mask creation and application
y = x[x % 2 == 0]
print('y :', y)

y : [0 2 4]


**Question:** What is the output?

```python
    y = x[x % 2]
    print('y :', y)
```

---
### 6.3. Fancy Indexing

**Principle:** Select data based on indices

**Application examples**

+ Splitting a dataset

    + Given: dataset of input-output examples

    + Goal: randomly split data into a train and test set 

+ Select k nearest neighbors

    + Given: list of distances

    + Goal: get class labels of k-nearest neighbors

    + Solution: 

        + select indices of the k smallest distances 

        + use indices to select class labels


**Fancy Indexing**

+ index arrays using arrays of indices

+ pass an array of indices to the indexing operator `[]`

+ resulting array has the same shape as the indexing array 

+ resulting array contains the values at the specified indices

+ can also be used with multi-dimensional arrays




**Example:** 1D arrays

In [6]:
# base array to be indexed
x = np.arange(10, 60, 10)
print('x :', x)

x : [10 20 30 40 50]


In [7]:
# select elements at indices 0, 2, and 4
indices = [0, 2, 4]

y = x[indices]
print('y :', y)

y : [10 30 50]


In [8]:
# select elements at indices 0, 1, 0, 1, 1, 0, 1
indices = [0, 1, 0, 1, 1, 0, 1]

y = x[indices]
print('y :', y)

y : [10 20 10 20 20 10 20]


In [9]:
# select elements at 1, 2, 3, 4 and reshape
indices = np.array(((1, 2), (3, 4)))

y = x[indices]
print(y)

[[20 30]
 [40 50]]


**Example:** multi-dimensional arrays

In [10]:
# base array to be indexed
A = np.arange(10, 70, 10).reshape(3, 2)
print(A)

[[10 20]
 [30 40]
 [50 60]]


In [11]:
# select elements at (0, 1), (2, 0), and (1, 0)
i = [0, 2, 1]
j = [1, 0, 0]

B = A[i, j]
print(B)

[20 50 30]


In [ ]:
# select rows with index 0 and 1
B = A[[0, 1]]
print(B)

In [ ]:
# select columns with index 0 and 2
B = A[:, [0, 1]]
print(B)

---

### 6.4. Summary

The following figure illustrates boolean and fancy indexing (source: scipy).

<br>

<div style="text-align: center;">
<img src="./figs/fancy_indexing.png" alt="tensors" width="600">
</div>

<br>