In [2]:
import numpy as np


## 5. Broadcasting


1. Overview

2. Broadcasting Rules

3. Example: Scalar and 1D Array

4. Example: 1D Array and 2D Array

5. Example: Column and Row

6. Example: Failure

7. Application: Standardization

8. Appendix A


---

### 5.1. Overview


**Vectorization:**

+ performs operations on entire array rather than iterating over individual elements

+ looping occurs in optimized, precompiled C instead of Python

+ requires that multiple array operands have compatible shape
    
<br>

**Broadcasting:**

+ term that describes how NumPy handles operations between arrays of different shapes

+ replicates the smaller array to match the shape of the larger array

+ allows for vectorized operations without making unnecessary data copies 

+ usually results in efficient algorithm implementations

<br>

**Note:** 

+ broadcasting specifies rules for making arrays of different shapes compatible for vectorization

+ broadcasting can sometimes lead to inefficient memory use and slow computation (see Appendix A)

---
### 5.2. Broadcasting Rules

1. **Rule 1:** If the arrays don't have the same number of dimensions, pad the shape of the array with fewer dimensions with ones on the left until both arrays have the same number of dimensions.

2. **Rule 2:** If one array has size one in one dimension, expand its size in that dimension to match the size of the other array in the same dimension.

3. **Rule 3:** If the arrays have different sizes in any dimension and neither is one, raise an error. 


---
### 5.3. Example: Scalar and 1D Array

In [3]:
a = np.array(5)         # scalar
x = np.arange(3)        # 1D array

print('a :', a)
print('x :', x)

a : 5
x : [0 1 2]


In [4]:
print('Broadcasted addition:')
z = x + a
print('z :', z)


Broadcasted addition:
z : [5 6 7]


In [5]:
print('Shapes and Dimensions:')
print('shape x :', x.shape)
print('shape a :', a.shape)
print('ndim  x :', x.ndim)
print('ndim  a :', a.ndim)

Shapes and Dimensions:
shape x : (3,)
shape a : ()
ndim  x : 1
ndim  a : 0


**Rule 1:** If the arrays don't have the same number of dimensions, pad the shape of the array with fewer dimensions with ones on the left until both arrays have the same number of dimensions.

+ `x.ndim = 1` is larger than `a.ndim = 0` 

+ pad shape `()` of `a` with ones from the left until `ndim = 1`

+ shape of `a` changes from `()` to `(1,)`

+ `a` becomes `a' = [5]`

**Rule 2:** If one array has size one in one dimension, expand its size in that dimension to match the size of the other array in the same dimension.

+ shapes of `x` and `a` differ in the first dimension (`3` vs `1`)

+ stretch first dimension of `a'` from `1` to `3` to obtain shape `(3,)`

+ `a'` becomes `a'' = [5, 5, 5]`

Finally, compute `x + a''`. The next figure illustrates broadcasting of the above example:

<br>

<div style="text-align: center;">
<img src="./figs/broadcasting_01.png" alt="tensors" width="450">
</div>

**Important Note** 

The stretching analogy shown in the following examples is only conceptual. NumPy uses the original scalar without actually making copies so that broadcasting operations are as memory and computationally efficient as possible.

---
### 5.4. Example: 1D Array and 2D Array

In [6]:
A = np.ones((3, 3))
b = np.arange(3)

print('Matrix A:')
print(A)
print()

print('Vector b:')
print(b)

Matrix A:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Vector b:
[0 1 2]


In [7]:
print('Broadcasted Addition:')
C = A + b
print(C)

Broadcasted Addition:
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [8]:
print('Shapes and Dimensions:')
print('shape A :', A.shape)
print('shape b :', b.shape)
print('ndim  A :', A.ndim)
print('ndim  b :', b.ndim)

Shapes and Dimensions:
shape A : (3, 3)
shape b : (3,)
ndim  A : 2
ndim  b : 1


**Rule 1:** If the arrays don't have the same number of dimensions, pad the shape of the array with fewer dimensions with ones on the left until both arrays have the same number of dimensions.

+ `A.ndim = 2` is larger than `b.ndim = 1` 

+ pad shape `(3,)` of `b` with ones from the left until `ndim = 2`

+ shape of `b` changes from `(3, )` to `(1, 3)`

+ `b` becomes `b' = [[0, 1, 2]]`

**Rule 2:** If one array has size one in one dimension, expand its size in that dimension to match the size of the other array in the same dimension.

+ shapes differ in the first dimension (`3` vs `1`)

+ stretch first dimension of `b'` from `1` to `3` to obtain shape `(3, 3)`

+ `b'` becomes `b'' = [[0, 1, 2], [0, 1, 2], [0, 1, 2]]`

Finally, compute `A + b''`. The next figure illustrates the above example:

<br>

<div style="text-align: center;">
<img src="./figs/broadcasting_02.png" alt="tensors" width="450">
</div>

<br>

---
### 5.5. Example: Column and Row

In [10]:
x = np.arange(3).reshape(3, 1)
y = np.arange(3)

print('column x :')
print(x)
print()
print('row y :')
print(y)

column x :
[[0]
 [1]
 [2]]

row y :
[0 1 2]


In [11]:
print('Broadcasted addition:')
z = x + y
print(z)

Broadcasted addition:
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [12]:
print('Shapes and Dimensions:')
print('shape x :', x.shape)
print('shape y :', y.shape)
print('ndim  x :', x.ndim)
print('ndim  y :', y.ndim)

Shapes and Dimensions:
shape x : (3, 1)
shape y : (3,)
ndim  x : 2
ndim  y : 1


**Rule 1:** If the arrays don't have the same number of dimensions, pad the shape of the array with fewer dimensions with ones on the left until both arrays have the same number of dimensions.

+ `x.ndim = 2` is larger than `y.ndim = 1` 

+ pad shape `(3,)` of `y` with ones from the left until `ndim = 2`

+ shape of `y` changes from `(3,)` to `(1, 3)`

+ `y` becomes `y' = [[0, 1, 2]]`

**Rule 2:** If one array has size one in one dimension, expand its size in that dimension to match the size of the other array in the same dimension.

+ shapes differ in the first and second dimensions 

+ stretch `x`:

    + stretch second dimension of `x` from `1` to `3` to obtain shape `(3, 3)`

    + `x` becomes `x' = [[0, 0, 0], [1, 1, 1], [2, 2, 2]]`

+ stretch `y`:

    + stretch first dimension of `y'` from `1` to `3` to obtain shape `(3, 3)`

    + `y'` becomes `y'' = [[0, 1, 2], [0, 1, 2], [0, 1, 2]]`

Finally, compute `x' + y''`. The next figure illustrates the above example:

<br>

<div style="text-align: center;">
<img src="./figs/broadcasting_03.png" alt="tensors" width="450">
</div>

<br>

---
### 5.6. Example: Failure

In [13]:
A = np.arange(6).reshape(2, 3)
b = np.arange(2)

print('Matrix A:')
print(A)
print()

print('Vector b:')
print(b)

Matrix A:
[[0 1 2]
 [3 4 5]]

Vector b:
[0 1]


In [14]:
print('Broadcasting fails')
C = A + b

Broadcasting fails


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [15]:
print('Shapes and Dimensions:')
print('shape A :', A.shape)
print('shape b :', b.shape)
print('ndim  A :', A.ndim)
print('ndim  b :', b.ndim)

Shapes and Dimensions:
shape A : (2, 3)
shape b : (2,)
ndim  A : 2
ndim  b : 1


**Rule 1:** If the arrays don't have the same number of dimensions, pad the shape of the array with fewer dimensions with ones on the left until both arrays have the same number of dimensions.

+ `A.ndim = 2` is larger than `b.ndim = 1` 

+ pad shape `(2,)` of `b` with ones from the left until `ndim == 2`

+ shape of `b` changes from `(2,)` to `(1, 2)`

+ `b` becomes `b' = [[0, 1]]`

**Rule 2:** If one array has size one in one dimension, expand its size in that dimension to match the size of the other array in the same dimension.

+ shapes differ in the first and second dimensions 

+ stretch first dimension of `b'` from `1` to `2` to obtain shape `(2, 2)`

+ `b'` becomes `b'' = [[0, 1], [0, 1]]`

**Rule 3:** If the arrays have different sizes in any dimension and neither is one, raise an error. 

+ shape `A` is `(2, 3)`

+ shape `b''` is `(2, 2)`

+ shapes disagree in last dimension (`3` vs `2`)

+ neither of both values is one

+ **Error**

---
### 5.7. Application: Standardization

Standardization is a common preprocessing step in data analysis and machine learning. It involves transforming the data so that it has zero mean and unit standard deviation.

Let $\mathbf{X} \in \mathbb{R}^{m \times n}$ be a feature matrix with $m$ observations and $n$ features. The Z-Transform (Standardization) of $\mathbf{X}$ is defined as:

$$
    \mathbf{Z} = \frac{\mathbf{X} - \mathbf{\mu}}{\mathbf{\sigma}}
$$

where $\mathbf{\mu} \in \mathbb{R}^n$ is the vector of column means and $\mathbf{\sigma} \in \mathbb{R}^n$ is the vector of column standard deviations. Subtraction and division are performed elementwise after broadcasting.

In detail: The elements of $\mathbf{\mu} = (\mu_1, \ldots, \mu_n)$ are given by:

$$
    \mu_j = \frac{1}{m}\sum_{i=1}^m x_{ij}
$$

and the squared elements of $\mathbf{\sigma} = (\sigma_1, \ldots, \sigma_n)$ are given by:

$$
    \sigma_j^2 = \frac{1}{m}\sum_{i=1}^m (x_{ij} - \mu_j)^2.
$$

Then the elements of $\mathbf{Z}$ are of the form

$$
    z_{ij} = \frac{x_{ij}-\mu_j}{\sigma_j}.
$$

For an implementation using brodacasting, see the notebook: [ztransform.ipynb](./ztransform.ipynb).


---
### 5.8. Appendix A

Example when looping is faster than broadcasting (example and answer are taken from [[>](https://stackoverflow.com/questions/49632993/why-python-broadcasting-in-the-example-below-is-slower-than-a-simple-loop)])

In [ ]:
A = np.random.random((1000, 100000))
x = A[0]

In [ ]:
def loop(A, x):
  n = A.shape[0]
  y = np.zeros(n)
  for i in range(n):
    y[i] = np.sum((A[i] - x)**2)
  return y

def bcast(A, x):
  return np.sum((A - x)**2, axis=1)

print('looping:')
%timeit loop(A, x) 

print('broadcasting:')
%timeit bcast(A, x)

**Reason:** In the broadcast version, each element of `A` is subtracted from `x`. By the time the last row of `A` is processed, the results of processing the first row have been evicted from the cache, so for the second step these differences are loaded back into the cache and squared. Finally, they are loaded and processed a third time for summation. Since `A` is quite large, parts of the cache are cleared at each step to accommodate all the data.

In the looped version, each row is processed completely in one smaller step, resulting in fewer cache misses and overall faster code.