In [1]:
import numpy as np

---
### Random Data Set

The data set consists of 20 observations, each of which has 3 features. The features are drawn from a uniform distribution over the interval [0, 10].

In [2]:
X = np.random.uniform(0, 10, (20, 3))
print(X)

[[6.53140345 8.34610363 8.66731159]
 [7.25244672 7.57082208 1.65056723]
 [1.75565544 2.72725078 9.96751375]
 [7.39804744 2.21485412 6.87023316]
 [8.99208538 7.85410212 4.63423882]
 [9.10296512 6.40871167 3.30725753]
 [7.48428342 4.96993838 0.60593505]
 [2.88855184 6.8362105  7.57081584]
 [3.13775761 7.75282914 9.98928723]
 [3.06706867 1.27577139 6.61288834]
 [4.71731947 2.77083655 7.58529383]
 [6.37000488 0.59866279 8.02150853]
 [9.22527427 1.05137547 0.09659293]
 [1.63575493 0.81940339 8.26724155]
 [9.59983645 5.20967323 2.44673643]
 [9.49652682 4.52911489 9.92496121]
 [9.58275999 4.42030019 5.19352626]
 [3.84997322 0.26022101 1.42828936]
 [6.04745606 8.20080576 4.35272997]
 [3.89968193 0.04904881 7.54154336]]


---
### Mean and Standard Deviation

In [3]:
avg = X.mean(0) # np.mean(X, axis = 0)
std = X.std(0)  # np.std(X, axis = 0)
print("avg =", avg)
print("std =", std)

avg = [6.10174266 4.19330179 5.7367236 ]
std = [2.71257043 2.89739452 3.1573403 ]


---
### Shapes

In [5]:
print('shape of X   :', X.shape)
print('shape of avg :', avg.shape)
print('shape of std :', std.shape)

shape of X   : (20, 3)
shape of avg : (3,)
shape of std : (3,)


---
### Z-Transform using Broadcasting

+ shape of X   : (20, 3)
+ shape of avg : (3, )
+ shape of std : (3, )
+ shape of Z   : (20, 3)

In [7]:
Z = (X - avg)/std
print(Z)

[[ 0.15839618  1.43328836  0.92818249]
 [ 0.42421168  1.16570949 -1.29417674]
 [-1.60220253 -0.50598944  1.33998548]
 [ 0.47788797 -0.68283683  0.35900773]
 [ 1.06553647  1.2634801  -0.34918148]
 [ 1.10641273  0.76462141 -0.76946602]
 [ 0.50967921  0.26804654 -1.62503502]
 [-1.18455572  0.91216736  0.58089787]
 [-1.09268501  1.22852698  1.34688162]
 [-1.11874477 -1.00694965  0.27750089]
 [-0.51037318 -0.49094634  0.58548337]
 [ 0.09889595 -1.24064534  0.72364228]
 [ 1.15150249 -1.08439714 -1.78635501]
 [-1.64640434 -1.16445944  0.8014714 ]
 [ 1.28958635  0.35078807 -1.04201222]
 [ 1.25150084  0.11590175  1.32650814]
 [ 1.28329104  0.0783457  -0.1720427 ]
 [-0.83012386 -1.35745435 -1.36457709]
 [-0.02001297  1.38314059 -0.43834161]
 [-0.81179854 -1.43033783  0.57162662]]


---
### Test

Test whether Z has approx. mean zero and standard deviation one.

In [9]:
print("avg(Z)=", Z.mean(0))
print("std(Z)=", Z.std(0))

avg(Z)= [-1.49880108e-16 -2.88657986e-16 -2.72004641e-16]
std(Z)= [1. 1. 1.]
