In [1]:
import numpy as np

## 2. NumPy Arrays

1. `ndarray`

2. Array Creation Functions

3. Attributes of an `ndarray`

4. Indexing and Slicing

5. Appendix

---

### 2.1. `ndarray`

NumPy's main data structure is the `ndarray`:

+ `ndarray` stands for n-dimensional array

+ used to represent vectors, matrices, and higher-dimensional arrays

+ efficient and convenient for performing operations on large numerical datasets

+ size of `ndarray` is usually fixed

<br>

In mathematics, we often work with numbers, vectors, and matrices. These concepts can be extended to higher dimensions:

<br>

<div style="text-align: center;">
<img src="./figs/tensors.png" alt="tensors" width="600">
</div>


---

### 2.2. Array Creation Functions

There are several ways to create arrays in NumPy. Below, are commonly used examples. For a complete list with deatiled description, see the NumPy documentation [[>](https://numpy.org/doc/stable/reference/routines.array-creation.html)].

| Numpy Function | Description |
| --- | --- |
| `array()` | creates an array from a list or tuple |
| `empty()` | creates an uninitialized array of a given shape |
| `zeros()` | creates an array filled with zeros |
| `ones()` | creates an array filled with ones |
| `full()` | creates an array filled with a specified value |
| `arange()` | creates an array of evenly-spaced values within an interval |
| `linspace()` | creates an array of evenly-spaced values within an interval |
| `logspace()` | creates an array of logarithmically-spaced within an interval |

In the following, we will discuss some of the functions shown in the table above.

<br>

<hr style="border-top: 0.5px dashed #7f7f7f;">

#### 2.2.1. `np.array()` 

Use `np.array()` to create an `ndarray` from list or tupels.

<br>

**1D Arrays**

In [2]:
x = np.array([1, 2, 3])

print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


<br>

**2D Arrays**

In [3]:
x = np.array([ [1, 2, 3], [4, 5, 6] ])

print(x)

[[1 2 3]
 [4 5 6]]


<br>

**3D Arrays**

In [4]:
x = np.array([
    [[1, 2, 3],
     [4, 5, 6]],
    [[0, 0, 0],
     [1, 1, 1]]])

print(x)

[[[1 2 3]
  [4 5 6]]

 [[0 0 0]
  [1 1 1]]]


<br>

**Remark:** The `ndarray` is composed of two stacked $(2 \times 3)$-matrices. It can be defined more compactly as: 

```python
    X_3d = np.array([ [ [1, 2, 3], [4, 5, 6] ], [ [0, 0, 0], [1, 1, 1] ] ])
```

<hr style="border-top: 0.5px dashed #7f7f7f;">

#### 2.2.2. `np.empty()`, `np.zeros()`, `np.ones()`

The functions `np.empty`, `np.zeros`, and `np.ones` all create a new ndarray of a specified shape, but differ in how the array is initialized. 

+ `np.empty` creates an uninitialized array

+ `np.zeros` fills the array with zeros

+ `np.ones` fills the array with ones

<br>

**1d array with `np.empty`:**

In [5]:
x = np.empty(3)

print(x)

[4.9e-324 9.9e-324 1.5e-323]


The values in the array `x` are whatever values were present in memory at that location before the array was created. These values are essentially random and should not be relied upon.

<br>

**2d array with `np.zeors`:**

In [6]:
x = np.zeros((2, 3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


<br>

**3d array with `np.ones`:**

In [7]:
# 3d array with ones
x = np.ones((2, 3, 4))
print(x)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]



**Remarks:**

+ The argument passed to one of the three functions determines the *shape* of the resulting `ndarray`. 

+ For 1D arrays, the argument can be a single non-negative integer. 

+ For higher-dimensional arrays, the argument must be a tuple or list of non-negative integers.

<hr style="border-top: 0.5px dashed #7f7f7f;">

#### 2.2.3. `numpy.arrange`

Recall Python's `range` function:

In [8]:
x = range(0, 11, 2)

print(list(x))

[0, 2, 4, 6, 8, 10]


`np.arange` is NumPy's counterpart of Python's `range`:

In [9]:
x = np.arange(0, 11, 2)

print(x)

[ 0  2  4  6  8 10]


<br>

**Syntax**

```python
    numpy.arange(start, stop, step)
```

+ Returns an `ndarray` with evenly spaced values within `[ start, stop )`, where `stop` is excluded

+ `start` is optional with default value `0`

+ `step` is optional with default value `1`

+ `start`, `stop`, `step` can be ints or floats


<br>

**Note:** `np.arrange` differs from `range` as follows:

+ `range` can only generate integer sequences, `np.arrange` can also generate float sequences

+ `range` only stores `start`, `stop`, and `step`, while `np.arrange` allocates memory for all elements
 
<br>
 
**Examples:**

In [10]:
x = np.arange(5)

print(x)

[0 1 2 3 4]


In [11]:
x = np.arange(5, 10)

print(x)

[5 6 7 8 9]


In [12]:
x = np.arange(0.5, 5, 0.5)

print(x)

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


<br>

**Question:** What is the output of the following code?

In [16]:
x = np.arange(1.0, 1.3, 0.1)

print(x)

[1.  1.1 1.2 1.3]


**Remark:** The inclusion of the value `1.3` in the output is due to the limitations of finite floating-point arithmetic. An explanation of why this error occurs can be found in the appendix at the end of this notebook. 

When using a non-integer step, such as 0.1, it is often better to use `np.linspace`.

<hr style="border: 0.5px solid #7f7f7f;">

#### 2.2.4. `numpy.linspace`

Consider the following example:

In [17]:
x = np.linspace(1, 5, 9)

print(*x, sep=', ')

1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0


**Syntax**

```python
    numpy.linspace(start, stop, num=50)
```

+ returns an `ndarray` with `num` evenly spaced values within the interval `[ start, stop ]`

+ `start` and `stop` 
    
    + determine the first and last value
    
    + can be ints and floats
    
    + must be provided

+ `num` 

    + number of elements within the interval `[ start, stop ]`
    
    + must be a non-negative integer
    
    + if `num == 0`, an empty `ndarray` is returned


<br>


**Examples:**

In [18]:
x = np.linspace(1, 10, 10)
print(x)

print()

x = np.linspace(0, 10)
print(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


---

### 2.3. Attributes of an `ndarray`

An `ndarray` object has several attributes. Below are some important ones:

+ `ndarray.shape`: tuple representing the number of elements along each axis.

+ `ndarray.ndim`: number of axes (dimensions) of the array.

+ `ndarray.size`: total number of elements in the array.

+ `ndarray.dtype`: data type of the array elements.

<hr style="border: 0.5px solid #7f7f7f;">

#### 2.3.1 Attributes related to the Shape


We consider the attribtues `shape`, `ndim`, `size` and introduce the conept of `axis`. For this, consider the $(3 \times 4)$-matrix 

$$
    A = \begin{pmatrix}
    1 & 2 & 3 & 4\\
    5 & 6 & 7 & 8\\
    9 & 10 & 11 & 12\\
    \end{pmatrix}
$$

NumPy refers to specific dimensions as **axes**. A 2d array with 3 rows and 4 columns has the following axes: 

+ axis 0: The first dimension (size 3) refers to the number of rows

+ axis 1: The second dimension (size 4) refers to the number of columns

<br>

**Attributes of a 2D Array:** The next example creates a 2D array with values from matrix $A$ and prints its shape, number of dimensions, and size.

In [19]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print(A)

print()
print('shape      :', A.shape)
print('dimensions :', A.ndim)
print('size       :', A.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

shape      : (3, 4)
dimensions : 2
size       : 12


<br>

**Attributes of a 3d Array:**

In [20]:
A = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
               
               [[13, 14, 15, 16],
                [17, 18, 19, 20],
                [21, 22, 23, 24]]])

print(A)

print()
print('shape      :', A.shape)
print('dimensions :', A.ndim)
print('size       :', A.size)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

shape      : (2, 3, 4)
dimensions : 3
size       : 24


A 3d array with shape (2, 3, 4) has the following axes: 

+ axis 0: The first dimension (size 2) refers to the depth

+ axis 1: The second dimension (size 3) refers to the number of rows

+ axis 2: The third dimension (size 4) refers to the number of columns

<br>

The figure below illustrates how the axes of `ndarrays` are organized:

<br>

<div style="text-align: center;">
<img src="./figs/axes.png" alt="tensors" width="600">
</div>


<hr style="border: 0.5px solid #7f7f7f;">


#### 2.3.2 Attribute `dtype`

+ The `dtype` attribute 

    + represents the data type of the items in the array.
    
    + parameter in array creation functions
    

+ Types 

    + NumPy provides a range of data types that you can use to construct arrays.

    + Types must fit to the precompiled C code.

    + Common data types include the Python native types `int`, `float`, and `bool`.


+ Setting the type

    + Specify the data type when creating an array with the `dtype` parameter.

    + Change the data type of an existing array with the `astype` method.

<br>

**Remarks:**

+ Items of an `ndarray` are of the same type.

+ For more details, see the documentation [[>](https://numpy.org/doc/stable/user/basics.types.html)].

<br>

**Example:** `dtype` is inferred by NumPy

In [21]:
# items are int
x = np.array([1, 2, 3])
print(x.dtype)

int64


In [22]:
# items are float
x = np.array([1., 2., 3.])
print(x.dtype)

float64


In [23]:
# items are ints and floats
x = np.array([1, 2, 3.])
print(x.dtype, x)

float64 [1. 2. 3.]


<br>

**Example:** specify `dtype` during array creation

In [24]:
x = np.array([1, 2, 3], dtype=float)
print(x.dtype, x)

float64 [1. 2. 3.]


<br>

**Example:** change `dtype` for existing array

In [27]:
x = np.array([1, 2, 3])
print('before:', x.dtype, x)

y = x.astype(float)
print('after:', y.dtype, y)

before: int64 [1 2 3]
after: float64 [1. 2. 3.]


**Remark:** the function `astype` returns a new copy of the array. 

---

### 2.4. Indexing and Slicing

Indexing in NumPy arrays works in a similar way to indexing in regular Python lists, but with some additional features: 

+ **Multidimensional indexing:** NumPy allows indexing of higher dimensional arrays with a single pair of square brackets.

+ **Boolean indexing:** NumPy allows indexing of arrays using boolean masks.

+ **Fancy indexing:** NumPy allows indexing of arays using other arrays or lists of indices.

Here, we consider multidimensional indexing. The other two forms will be covered later.

<br>

---

### 2.4.1. Multidimensional Indexing

+ NumPy arrays can be indexed as Python's sequence types. 

+ Multidimensional arrays can be additionally indexed with a single pair of square brackets and a comma separated list of indices.

In [28]:
x = np.array([[1, 2, 3], 
              [4, 5, 6]])

print('Python style :', x[0][2])
print('NumPy style  :', x[0, 2])

Python style : 3
NumPy style  : 3


---
### 2.4.2. Slicing 

Slicing in NumPy arrays works in a similar way to slicing in regular Python lists, but also with some additional features:

+ **Multidimensional slicing:** In NumPy allows slice arrays with multiple dimensions using a single pair of square brackets.

+ **Views instead of copies:** Slicing a regular Python list creates a new list containing a copy of the selected items. However, when slicing a NumPy array, a view of the original array is returned instead of a copy. This means that changes made to the view will affect the original array.


<br>

**Example 1:**

In [29]:
x = np.array([[1, 2, 3], 
              [4, 5, 6],
              [7, 8, 9]])

print('1 bracket  :', x[1:, 1:], sep='\n')
print()
print('2 brackets :', x[1:][1:], sep='\n') 

1 bracket  :
[[5 6]
 [8 9]]

2 brackets :
[[7 8 9]]


**Note:** 

+ Slicing `x[1:]` returns the view `v = [ [4, 5, 6], [7, 8, 9] ]`

+ Slicing `v[1:] = x[1:][1:]` returns the view `[[7, 8, 9]]`

**Example 2:** 


<div style="text-align: left;">
<img src="./figs/slicing.png" alt="tensors" width="400">
</div>


---

### 2.5. Appendix

Consider the following code:  

```python
    x = np.arange(1.0, 1.3, 0.1)
```

The resulting array `x` erroneously includes the value `1.3`. This happens because `np.arange` calculates the number of steps `n` required to reach `stop` from `start` using the formula`

```python
    n = ceil((stop - start) / step)
```

where `ceil(a)` rounds to the the next integer equal or larger than `a`. Then `np.arange` uses a `for` loop to calculate `n` elements for the array `x`. However, due to the limitations of floating-point representation, the number `n` can be too large, as demonstrated in the following code snippet:

In [ ]:
start = 1.0
stop = 1.3
step = 0.1

n = ((stop - start) / step)
print("n before rounding up :", n)
n = int(np.ceil(n))
print("n after rounding up  :", n)

print()
print('values of array x:')
x = start
for i in range(n):
    print(x)
    x += step 

Note that when using a `while` loop, the value `1.3` is not included into the array:

In [ ]:
start = 1.0
stop = 1.3
step = 0.1

print('values of array x:')
x = start
while x < stop:
    print(x)
    x += step