In [1]:
import numpy as np


## 3. Operations on NumPy Arrays


1. Overview

2. Arithmetic Operations

3. Logical Operations

4. Comparison Operations

5. Math Functions

6. Reduction Functions

---

### 3.1. Overview


This sections covers some common operations on NumPy arrays. The functions in 3.2 - 3.5 are ufuncs:

+ `ufuncs`

    + short for 'universal functions'

    + functions that operate element-wise on arrays

    + efficient, because they are implemented in C 

    + broadcasting: can operate on arrays of different (but compatible) shapes

<br>

+ Examples: 

    + arithmetic operators
    
    + logical operators

    + comparison operators
    
    + math functions: sin, cos, exp, log, ... 
    
<br>
    
+ Documentation:

    + [Mathematical functions](https://numpy.org/doc/stable/reference/routines.math.html#mathematical-functions)

    + [Universal functions](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs) 
    
    + [Sums, products, and differences](https://numpy.org/doc/stable/reference/routines.math.html#sums-products-differences)

    + [Statistics](https://numpy.org/doc/stable/reference/routines.statistics.html#statistics)

    + [Extrema finding](https://numpy.org/doc/stable/reference/routines.math.html#extrema-finding)

    
<br>

+ **Note:** 

    + There are many more important functions than are covered here. 

    + Functions have additional parameters not covereed here.
    
    + Search the documentation before hand coding your own function. 


<br>

**Example:** elementwise addition with `+`

In [2]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

z = x + y

print(z)

[5 7 9]


---
### 3.2 Arithmetic Operations

The following table shows the arithmetic operators and their corresponding ufuncs:


<div style="text-align: left;">
<img src="./figs/ufuncs_arithmetic.png" alt="tensors" width="550">
</div>

Arithmetic operators such as `+`, `-`, and `*` automatically call their respective ufuncs `np.add`, `np.subtract`, and `np.multiply` when used on arrays. Using ufuncs directly provides additional functionality, such as specifying an output array with the `out` parameter to reduce memory usage and improve performance.

**Example:** elementwise addition with `add`

In [4]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print('x :', x)
print('y :', y)

z = np.add(x, y)
print('z :', z)

np.add(2 * x, y, out=z)
print('z :', z)

x : [1 2 3]
y : [4 5 6]
z : [5 7 9]
z : [ 6  9 12]


---

### 3.3. Logical Operations

The following table shows the bitwise logical operators and their corresponding ufuncs when applied to boolean ndarrays:

<div style="text-align: left;">
<img src="./figs/ufuncs_logical.png" alt="tensors" width="550">
</div>

**Warning:** Combining arrays with the Python keywords `and` and `or` will result in a ValueError. 

<br>

**Example:**

In [7]:
x = np.array([1, 0, 0])
y = np.array([2, 2, 0])

print('x   |   y :', x | y)
print('x np.or y :', np.logical_or(x, y))

# raises ValueError:
#print('x or y :', x or y)

x   |   y : [3 2 0]
x np.or y : [ True  True False]


**ValueError:** There is no one commonly understood way to evaluate an array in Boolean context. Consider the array `x = [1, 0]` for example. It could be possibly evaluated as 

+ `True` because at least one element is evaluated as `True`

+ `False` because not all elements are evaluated as `True`

+ `True` because the array is not empty. 

The NumPy developers refused to decide for one alternative and decided to raise a ValueError whenever arrays are evaluated in Boolean context using Python's `and` and `or`.

---
### 3.4. Comparison Operators

The following table shows the logical operators and their corresponding ufuncs:

<div style="text-align: left;">
<img src="./figs/ufuncs_comparison.png" alt="tensors" width="550">
</div>


**Example:** Operator precedence

In [9]:
x = np.array([0, 1, 2, 3, 4])
y = np.array([0, 0, 2, 4, 4])

# use parentheses
print((x > 2) | (x == y))

# ValueError:
print(x > 2 | x == y)

[ True False  True  True  True]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**ValueError:** The expression `x > 2 | x == y` is evaluated as follows:

1. `|` has highest precedence. The expression `2 | x` is evaluated first and results in an array `z`.

2. The expression `x > z == y` is a chain of the form `(x > z) and (z == y)`. 

Since two arrays are evaluated in Boolean context, NumPy raises a ValueError (see above).

**Note:** We didn't cover bitwise operators. They have higher precedence than comparision operators but lower precedence than arithmetic operators. 

---

### 3.5. Math Functions


Universal functions include common math operations [[>](https://numpy.org/doc/stable/reference/ufuncs.html#math-operations)] and trigonometric functions [[>](https://numpy.org/doc/stable/reference/ufuncs.html#trigonometric-functions)]  such as

+ Math operations: `np.exp`, `np.log`, `np.tan`, ...

+ Trigonemetric functions: `np.sin`, `np.cos`, `np.tan`, ...


**Example:**

In [21]:
PI = np.pi

x = np.array([0, PI/2, PI, 3*PI/2, 2*PI])
y = np.sin(x)

# output (suppress scientific notation)
np.set_printoptions(precision=2, suppress=True)
print('x      :', x)
print('sin(x) :', y)

x      : [0.   1.57 3.14 4.71 6.28]
sin(x) : [ 0.  1.  0. -1. -0.]


---
### 3.6. Reduction Functions

<hr style="border-top: 0.5px dashed #7f7f7f;">

#### 3.6.1. Overview

Reduction functions aggregate the values of an arrays. The following functions are some of the most commonly used reduction functions in data science and machine learning:

<div style="text-align: left;">
<img src="./figs/ufuncs_reduction.png" alt="tensors" width="500">
</div>


<br>


**Remarks:** Reduction functions are not ufuncs. 


<hr style="border-top: 0.5px dashed #7f7f7f;">

#### 3.6.2 Example: `np.sum` for 1D Arrays

`np.sum` returns the sum of all elements of a given 1d array:

In [10]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [11]:
s = np.sum(x)
print(s)

6


<hr style="border-top: 0.5px dashed #7f7f7f;">

#### 3.6.3 Example: `np.sum` for 2D Arrays

`np.sum` returns the sum of all elements of a given 2d array:

In [12]:
x = np.arange(6).reshape(-1,2)
print(x)

[[0 1]
 [2 3]
 [4 5]]


In [13]:
s = np.sum(x)
print(s)

15


<hr style="border-top: 0.5px dashed #7f7f7f;">

#### 3.6.4 Example: `np.sum` for 2D Arrays along an axis

The `np.sum()` function has an `axis` parameter that defaults to `None`. If unspecified, it returns the sum of all elements in the array. Specifying `axis=0` or `axis=1` returns the sum for each column or row, respectively.

<div style="text-align: left;">
<img src="./figs/sum_axis.png" alt="tensors" width="450">
</div>

<br>

**Sum along axis = 0:**

In [14]:
x = np.arange(6).reshape(-1,2)
print('matrix:')
print(x)

print()
print('sum(x, axis=0):')
s = np.sum(x, axis=0)
print(s)

matrix:
[[0 1]
 [2 3]
 [4 5]]

sum(x, axis=0):
[6 9]


**Sum along axis = 1:**

In [15]:
x = np.arange(6).reshape(-1,2)
print('matrix:')
print(x)

print()
print('sum(x, axis=1):')
s = np.sum(x, axis=1)
print(s)

matrix:
[[0 1]
 [2 3]
 [4 5]]

sum(x, axis=1):
[1 5 9]
